# Generated by Django 6.1 on 2026-08-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('student', 'level', 'semester'), name='unique_student_semester'),
        ),
    ]
