# Generated by Django 6.1 on 2026-09-03 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_examreminder_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRetake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Retake'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('retake_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retake_records', to='calculator.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.student')),
            ],
        ),
    ]
