# Generated by Django 6.1 on 2026-09-03 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_courseretake'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_code', models.CharField(blank=True, max_length=30)),
                ('task_type', models.CharField(choices=[('assignment', 'Assignment'), ('test', 'Test'), ('project', 'Project'), ('study', 'Study Session'), ('reading', 'Reading'), ('presentation', 'Presentation'), ('other', 'Other')], default='assignment', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_tasks', to='calculator.student')),
            ],
        ),
    ]
