"""
Django settings for cgpa_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""


from pathlib import Path
import os

import dj_database_url


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY / ENVIRONMENT
# =========================================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "change-this-development-key-before-production"
)


DEBUG = os.environ.get(
    "DEBUG",
    "True"
).lower() == "true"


# =========================================================
# ALLOWED HOSTS
# =========================================================

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
]


# Render automatically provides the deployed hostname.
RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    "RENDER_EXTERNAL_HOSTNAME"
)


if RENDER_EXTERNAL_HOSTNAME:

    ALLOWED_HOSTS.append(
        RENDER_EXTERNAL_HOSTNAME
    )


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    "django.contrib.admin",

    "django.contrib.auth",

    "django.contrib.contenttypes",

    "django.contrib.sessions",

    "django.contrib.messages",

    "django.contrib.staticfiles",

    "calculator",

]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise must come directly after SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = "cgpa_project.urls"


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {

        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],

        },

    },

]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = "cgpa_project.wsgi.application"


# =========================================================
# DATABASE
# =========================================================

DATABASES = {

    "default":
        dj_database_url.config(

            # Local development continues to use SQLite.
            default=(
                f"sqlite:///"
                f"{BASE_DIR / 'db.sqlite3'}"
            ),

            conn_max_age=600,

            conn_health_checks=True,

        )

}


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {

        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",

    },

    {

        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",

    },

    {

        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",

    },

    {

        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",

    },

]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = "en-us"


TIME_ZONE = "UTC"


USE_I18N = True


USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = "/static/"


# collectstatic will copy all static files here.
STATIC_ROOT = BASE_DIR / "staticfiles"


# Django 6 storage configuration.
STORAGES = {

    "default": {

        "BACKEND":
            "django.core.files.storage.FileSystemStorage",

    },

    "staticfiles": {

        "BACKEND":
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage",

    },

}


# =========================================================
# MEDIA / USER UPLOADS
# =========================================================

MEDIA_URL = "/media/"


MEDIA_ROOT = BASE_DIR / "media"


# =========================================================
# EMAIL SETTINGS
# =========================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)


EMAIL_HOST = "smtp.gmail.com"


EMAIL_PORT = 587


EMAIL_USE_TLS = True


EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    ""
)


EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    ""
)


DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER
)


# =========================================================
# LOGIN / LOGOUT
# =========================================================

LOGIN_URL = "/login/"


LOGIN_REDIRECT_URL = "/"


LOGOUT_REDIRECT_URL = "/login/"


# =========================================================
# GENERAL SECURITY SETTINGS
# =========================================================

SECURE_CONTENT_TYPE_NOSNIFF = True


X_FRAME_OPTIONS = "DENY"


SECURE_REFERRER_POLICY = "same-origin"


# =========================================================
# PRODUCTION SECURITY
# =========================================================

if not DEBUG:

    # Render terminates HTTPS before forwarding
    # requests to Django.
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https"
    )


    SESSION_COOKIE_SECURE = True


    CSRF_COOKIE_SECURE = True


    # Allow POST requests from the Render domain.
    CSRF_TRUSTED_ORIGINS = [
        "https://*.onrender.com",
    ]


    # HSTS can be increased later after deployment
    # is confirmed stable.
    SECURE_HSTS_SECONDS = 3600


    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


    SECURE_HSTS_PRELOAD = False